# Background on Psychophysics {-}

We wanted to find a study that would be fun, easy, and understandable to replicate.
We *failed*.
So we took an experiment that was easy to implement on an computer from:

> Reese, T. W., Reese, E. P., Volkmann, J., & Corbin, H. H. (Eds.). (1953). Psychophysical research: summary report, 1946-1952 (Vol. 131, No. 1-5). Office of Naval Research.
> This report is a compilation of more than seventy experiments in the area of visual discrimination.
> Such topics as estimating bearing, estimating the number of targets, coding of controls, etc. are covered.
> In compiling the data it became evident that some of the results have immediate specific military application, some have general application, and others provide basic research information.
> Because of this, it was not feasible to present these results with specific recommendations for incorporating them into military training and equipment problems.
> As a result, this report is primarily written for the military psychologist who will undoubtedly have many opportunities, now and in the future, to employ these research answers.

If you are really interested in the background, [we uploaded the original description of the experiment](https://aaronpeikert.github.io/repro-collab/assets/Psychophysical%20Research%20Summary%201946-1952.pdf).
